### ISSUE TITLE
Validacion TypeScrip de Registro de Usuario

### ISSUE THREAD

**Issue by marbeaper** [FSAgentesPublicos2022/grupo12-fsap2022-g12#12]
Validar con TypeScript el formulario Registro de Usuario creado en bootstap.

**Comment by blasichea** [comment]
Se utilizó formulario reactivo para modelar y validar los datos de registro de usuario. Validaciones integradas y personalizadas, en conjunto con las propiedades de inputs según el tipo de dato que va a contener
