### ISSUE TITLE
Interfaz de compra venta

### ISSUE THREAD

**Issue by blasichea** [FSAgentesPublicos2022/grupo12-fsap2022-g12#2]
Como usuario necesito una interfaz donde realizar compras y ventas de criptomonedas

**Comment by marbeaper** [comment]
Se creo Historia de Usuario, se ingreso al Sprint 0 y al Tablero Kanban del Proyecto en la tarjeta to do

**Comment by marbeaper** [comment]
Se creo compra_venta.html. Se soluciona esta Isuue.
