### ISSUE TITLE
Dashboard de Usuario

### ISSUE THREAD

**Issue by romansad** [FSAgentesPublicos2022/grupo12-fsap2022-g12#4]
Como usuario de la plataforma necesito gestionar las distintas funcionalidades, desde una pagina para mejor organizacion e identificación  visual

**Comment by marbeaper** [comment]
Se creo Historia de Usuario, se ingreso al Sprint 0 y al Tablero Kanban del Proyecto en la tarjeta to do

**Comment by marbeaper** [comment]
Se creo dashboard.html.  Se soluciona esta Issue.
