### ISSUE TITLE
Administracion de usuarios

### ISSUE THREAD

**Issue by romansad** [FSAgentesPublicos2022/grupo12-fsap2022-g12#5]
Como administrador de la plataforma necesito poder gestionar los usuarios de la plataforma, para las habilitaciones e inhabilitaciones de los mismos dentro de la plataforma.

**Comment by marbeaper** [comment]
Se creo Historia de Usuario, se ingreso al Sprint 0 y al Tablero Kanban del Proyecto en la tarjeta to do

**Comment by marbeaper** [comment]
Se creo pagina html. Se cierra el Sprint
