### ISSUE TITLE
Historial de transacciones

### ISSUE THREAD

**Issue by romansad** [FSAgentesPublicos2022/grupo12-fsap2022-g12#6]
Como usuario de la plataforma, necesito visualizar mi historial de compras y ventas de criptos para el analisis de inversiones en la plataforma.

**Comment by marbeaper** [comment]
Se creo Historia de Usuario, se ingreso al Sprint 0 y al Tablero Kanban del Proyecto en la tarjeta to do

**Comment by marbeaper** [comment]
Se creo transacciones.html.  Se soluciona esta Issue.
