### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by blasichea** [FSAgentesPublicos2022/grupo12-fsap2022-g12#7]
Como usuario quiero una página de presentación y bienvenida para conocer la aplicación y sus detalles

**Comment by romansad** [comment]
Precondiciones: 
Usuario debe acceder mediante navegador web chrome/firefox/brave, a la url https://xxx.com.ar
La version del navegador para el caso de chrome debe ser >80 para firefox >a 79

**Comment by romansad** [comment]
Pruebas de aceptacion:
